
package iswawsia_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "imatest", targetNamespace = "http://iswa.ws.ia.source.code")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Imatest {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewEleve", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.AddNewEleve")
    @ResponseWrapper(localName = "addNewEleveResponse", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.AddNewEleveResponse")
    public void addNewEleve(
        @WebParam(name = "arg0", targetNamespace = "")
        Eleve arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFicheEleve", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.GetFicheEleve")
    @ResponseWrapper(localName = "getFicheEleveResponse", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.GetFicheEleveResponse")
    public int getFicheEleve(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setFicheEleve", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.SetFicheEleve")
    @ResponseWrapper(localName = "setFicheEleveResponse", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.SetFicheEleveResponse")
    public void setFicheEleve(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEleveDifficulty", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.GetEleveDifficulty")
    @ResponseWrapper(localName = "getEleveDifficultyResponse", targetNamespace = "http://iswa.ws.ia.source.code", className = "iswawsia_package.GetEleveDifficultyResponse")
    public int getEleveDifficulty(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
