
package iswawsia_package;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "imatest", targetNamespace = "http://code.source.ia.ws.iswa/", wsdlLocation = "http://localhost:8080/iswawsia/imatest?wsdl")
public class Imatest_Service
    extends Service
{

    private final static URL IMATEST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(iswawsia_package.Imatest_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = iswawsia_package.Imatest_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/iswawsia/imatest?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/iswawsia/imatest?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IMATEST_WSDL_LOCATION = url;
    }

    public Imatest_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Imatest_Service() {
        super(IMATEST_WSDL_LOCATION, new QName("http://code.source.ia.ws.iswa/", "imatest"));
    }

    /**
     * 
     * @return
     *     returns Imatest
     */
    @WebEndpoint(name = "imatestport")
    public Imatest getImatestport() {
        return super.getPort(new QName("http://code.source.ia.ws.iswa/", "imatestport"), Imatest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Imatest
     */
    @WebEndpoint(name = "imatestport")
    public Imatest getImatestport(WebServiceFeature... features) {
        return super.getPort(new QName("http://code.source.ia.ws.iswa/", "imatestport"), Imatest.class, features);
    }

}
